name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install moban
    - name: Sync GitHub's master template repository of templates
      run: .github/scripts/sync-github.sh
    - name: Run moban then lint templates for white space
      run: |
        moban
        .github/scripts/check-whitespace.sh
        git diff --exit-code
    - name: Rebuild gitignore.io
      run: .github/scripts/build-parent.sh
